spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.compatibility-verifier.enabled=false

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.loadbalancer.ribbon.enabled=false

management.endpoints.web.exposure.include=gateway,routes,health
management.endpoint.gateway.enabled=true

# Routes
spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**

spring.cloud.gateway.routes[2].id=price-service
spring.cloud.gateway.routes[2].uri=lb://price-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/price/**

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=lb://cart-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/cart/**

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://order-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/order/**

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://notification-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/notification/**


# JWT secret (must be same as customer-service!)
jwt.secret=ecommerce-microservices-secret-key-very-long-string-2024

# Public endpoints (no token needed)
public.endpoints=/customer/register,/customer/login

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
